[tool.poetry]
name = "comap-rag-pipeline"
version = "0.1.0"
description = "RAG preprocessing pipeline for COMAP MCM/ICM"
authors = ["Emiya <Emiyaaaaaaaa@users.noreply.github.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
langchain-core = "^0.3.0"
langchain-text-splitters = "^0.3.0"
langgraph = "^0.2.0"
langchain-google-genai = "^2.0.0"
python-docx = "^1.2.0"
chromadb = "^1.5.5"
python-dotenv = "^1.2.2"
google-genai = "^1.68.0"
fastapi = "^0.135.2"
uvicorn = "^0.42.0"
pymupdf = "^1.27.2.2"
python-multipart = "^0.0.22"
matplotlib = "^3.10.8"
seaborn = "^0.13.2"
sqlalchemy = "^2.0.38"
email-validator = "^2.2.0"
passlib = {extras = ["cryptography"], version = "^1.7.4"}
bcrypt = "4.0.1"
aiosqlite = "^0.22.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
